[package]
name = "welds"
authors = ["Lex Childs <lexchilds@gmail.com>"]
version = "1.0.0"
edition = "2021"
license = "BSD-3-Clause"
categories = ["Database interfaces", "database"]
keywords = ["orm", "postgres", "mssql", "mysql", "sqlite"]
readme = "README.md"
repository = "https://github.com/weldsorm/welds"
description = "An async ORM for (postgres, mssql, mysql, sqlite)"

[dependencies]
welds-connections = { path="../welds-connections", version = "^1.0" }
async-trait = "0.1"
log = "0.4"
colored = { version="2", optional = true }
thiserror = "1.0.57"
welds-macros = { path="../welds-macros", version = "^1.0" }

[features]
"default" = []
"postgres" = ["welds-connections/postgres"]
"mysql" = ["welds-connections/mysql"]
"mssql" = ["welds-connections/mssql"]
"sqlite" = ["welds-connections/sqlite"]
"full" = ["postgres", "mysql", "mssql", "sqlite", "check", "detect", "migrations" ]
"check" = []
"detect" = []
"migrations" = []

#"detect" = []
#"check" = ["detect", "dep:colored"]
#"example_objects" = []
#"postgres" = ["sqlx/postgres", "welds-macros/postgres"]
#"mysql" = ["sqlx/mysql", "welds-macros/mysql"]
#"sqlite" = ["sqlx/sqlite", "welds-macros/sqlite"]
#"mssql" = ["welds-sqlx-mssql", "welds-macros/mysql"]


#[profile.dev.package.sqlx-macros]
#opt-level = 3


[dev-dependencies]
#async-std = { version = "1", features = ["attributes"] }
#sqlx = { version = "0.7", features = [ "runtime-async-std", "tls-rustls", "macros"] }
welds = { path="./", features=["full"] }
futures = {version= "0.3" }
welds-connections = { path="../welds-connections", version = "^1.0", features=["full"] }
