[package]
name = "welds"
authors = ["Lex Childs <lexchilds@gmail.com>"]
version = "0.2.1"
edition = "2021"
license = "BSD-3-Clause"
categories = ["Database interfaces", "database"]
keywords = ["orm", "postgres", "mssql", "mysql", "sqlite"]
readme = "README.md"
repository = "https://github.com/weldsorm/welds"
description = "An async ORM for (postgres, mssql, mysql, sqlite)"

[dependencies]
sqlx = { version = "0.7", features = [ "macros"] }
welds-macros = { path="../welds-macros", version = "^0.2" }
welds-sqlx-mssql = { path="../../welds-sqlx-mssql", version = "1.7", optional=true }
async-trait = "0.1"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
colored = { version="2", optional = true }

[features]
"default" = []
"detect" = []
"check" = ["detect", "dep:colored"]
"example_objects" = []
"postgres" = ["sqlx/postgres", "welds-macros/postgres"]
"mysql" = ["sqlx/mysql", "welds-macros/mysql"]
"sqlite" = ["sqlx/sqlite", "welds-macros/sqlite"]
"mssql" = ["welds-sqlx-mssql", "welds-macros/mysql"]


[profile.dev.package.sqlx-macros]
opt-level = 3


[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
sqlx = { version = "0.7", features = [ "runtime-async-std", "tls-rustls", "macros"] }
welds = { path="./", features=["postgres", "mysql", "mssql", "sqlite", "detect", "check"] }


