[package]
name = "welds"
authors = ["Lex Childs <lexchilds@gmail.com>"]
version = "0.1.4"
edition = "2021"
license = "BSD-3-Clause"
categories = ["Database interfaces", "database"]
keywords = ["orm", "postgres", "mssql", "mysql", "sqlite"]
readme = "README.md"
repository = "https://github.com/weldsorm/welds"
description = "An async ORM for (postgres, mssql, mysql, sqlite)"

[dependencies]
sqlx = { version = "^0.6", features = [ "macros"] }
welds-macros = { path="../welds-macros", version = "^0.1" }
async-trait = "0.1"
thiserror = "1.0.40"
anyhow = "1.0.70"
log = "0.4.17"
colored = { version="2", optional = true }

[features]
"default" = []
"detect" = []
"check" = ["detect", "dep:colored"]
"postgres" = ["sqlx/postgres", "welds-macros/postgres"]
"mysql" = ["sqlx/mysql", "welds-macros/mysql"]
"mssql" = ["sqlx/mssql", "welds-macros/mssql"]
"sqlite" = ["sqlx/sqlite", "welds-macros/sqlite"]


[profile.dev.package.sqlx-macros]
opt-level = 3


[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
sqlx = { version = "0.6", features = [ "runtime-async-std-rustls",  "macros"] }
welds = { path="./", features=["postgres", "mysql", "mssql", "sqlite", "detect", "check"] }


