[package]
name = "welds-macros"
authors = ["Lex Childs <lexchilds@gmail.com>"]
version = "0.1.9"
edition = "2021"
license = "BSD-3-Clause"
categories = ["Database interfaces", "database"]
keywords = ["orm", "postgres", "mssql", "mysql", "sqlite"]
readme = "README.md"
repository = "https://github.com/lex148/welds"
description = "Macros for the welds ORM"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^1.0", features = ["extra-traits"] }
log = "^0.4"
welds-sqlx-mssql = { path="../../welds-sqlx-mssql", version = "0.7.0-alpha.3", optional=true }
sqlx = { version = "0.7.0-alpha.3" }
quote = "^1.0"
proc-macro2 = "1"

[features]
"default" = []
"postgres" = ["sqlx/postgres"]
"mysql" = ["sqlx/mysql"]
"sqlite" = ["sqlx/sqlite"]
"mssql" = ["welds-sqlx-mssql"]

[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
sqlx = { version = "0.7.0-alpha.3", features = [ "runtime-async-std", "tls-rustls", "macros"] }
welds-macros = { path="./", features=["postgres", "mysql",  "sqlite"] }


