[package]
name = "welds-macros"
authors = ["Lex Childs <lexchilds@gmail.com>"]
version = "0.1.3"
edition = "2021"
license = "BSD-3-Clause"
categories = ["Database interfaces", "database"]
keywords = ["orm", "postgres", "mssql", "mysql", "sqlite"]
readme = "README.md"
repository = "https://github.com/lex148/welds"
description = "Macros for the welds ORM"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^1.0", features = ["extra-traits"] }
log = "^0.4"
sqlx = "0.6"
quote = "^1.0.2"
proc-macro2 = "1"

[features]
"default" = []
"postgres" = ["sqlx/postgres"]
"mysql" = ["sqlx/mysql"]
"mssql" = ["sqlx/mssql"]
"sqlite" = ["sqlx/sqlite"]

[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
sqlx = { version = "0.6", features = [ "runtime-async-std-rustls",  "macros"] }
welds-macros = { path="./", features=["postgres", "mysql", "mssql", "sqlite"] }


